apiVersion: v1
kind: Secret
metadata:
  name: my-page-auth
type: kubernetes.io/basic-auth
stringData:
  username: foo
  password: s3cr3t
---
apiVersion: uroperator.brennerm.github.io/v1beta1
kind: UptimeRobotMonitor
metadata:
  name: my-custom-monitor
spec:
  url: https://brennerm.github.io
  type: HTTPS
  interval: 600
  httpAuthType: BASIC_AUTH
  httpAuthSecret: my-page-auth # reference to the above secret


