apiVersion: v1
kind: Secret
metadata:
  name: my-public-status-page-password
type: Opaque
data:
  password: czNjcjN0 # base64 encoded s3cr3t
---
apiVersion: uroperator.brennerm.github.io/v1beta1
kind: PublicStatusPage
metadata:
  name: my-public-status-page
spec:
  monitors: "0" # will include all monitors
  passwordSecret: "my-public-status-page-password" # reference to the above secret
